# Enable all actuator endpoints FOR DEMO PURPOSES ONLY!
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: goodreads-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://goodreads-eureka:8761/eureka
